#ifndef MY_C_UTILS_PRIMITIVES_H
#define MY_C_UTILS_PRIMITIVES_H

#include "my_c_utils/free.h"
#include "my_c_utils/clone.h"
#include "my_c_utils/result.h"
#include "my_c_utils/tipos.h"
#include "my_c_utils/hash_defaults.h"

#define PRIMITIVE_CONFIG(Type)           \
	TRIVIAL_FREE(Type, ref_##Type value) \
	RESULT_CONFIG(Type)                  \
	RESULT_CONFIG(ref_##Type)            \
	TRIVIAL_CLONE(Type)                  \
	PRIMITIVE_HASH_EQUALS(Type)

/* Instantiate the primitive helpers in a safe order. */
PRIMITIVE_CONFIG(Bool)
PRIMITIVE_CONFIG(Char)
PRIMITIVE_CONFIG(SChar)
PRIMITIVE_CONFIG(UChar)
PRIMITIVE_CONFIG(Short)
PRIMITIVE_CONFIG(UShort)
PRIMITIVE_CONFIG(Int)
PRIMITIVE_CONFIG(UInt)
PRIMITIVE_CONFIG(Long)
PRIMITIVE_CONFIG(ULong)
PRIMITIVE_CONFIG(LongLong)
PRIMITIVE_CONFIG(ULongLong)
PRIMITIVE_CONFIG(Float)
PRIMITIVE_CONFIG(Double)
PRIMITIVE_CONFIG(LongDouble)
PRIMITIVE_CONFIG(WChar)

PRIMITIVE_CONFIG(I8)
PRIMITIVE_CONFIG(U8)
PRIMITIVE_CONFIG(I16)
PRIMITIVE_CONFIG(U16)
PRIMITIVE_CONFIG(I32)
PRIMITIVE_CONFIG(U32)
PRIMITIVE_CONFIG(I64)
PRIMITIVE_CONFIG(U64)
PRIMITIVE_CONFIG(IntPtr)
PRIMITIVE_CONFIG(UIntPtr)
PRIMITIVE_CONFIG(IntMax)
PRIMITIVE_CONFIG(UIntMax)
PRIMITIVE_CONFIG(PtrDiff)
PRIMITIVE_CONFIG(Size)

#endif // MY_C_UTILS_PRIMITIVES_H
